# Generated by Django 4.2.7 on 2023-12-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='meaning',
        ),
        migrations.AddField(
            model_name='word',
            name='meanings',
            field=models.ManyToManyField(related_name='words', to='dictionaryapp.meaning'),
        ),
    ]
