# Generated by Django 4.2.7 on 2023-12-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaryapp', '0002_meaning_remove_word_meaning_word_meanings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanglaToEnglishWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bangla_word', models.CharField(max_length=100, unique=True)),
                ('english_meaning', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BanglaWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('meaning', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EnglishWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('meaning', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='meanings',
        ),
        migrations.DeleteModel(
            name='Meaning',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
