# Generated by Django 4.2.7 on 2023-12-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaryapp', '0004_en_rename_banglaword_word_delete_banglatoenglishword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('meaning', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='en',
        ),
    ]
