# Generated by Django 4.2.7 on 2023-12-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaryapp', '0005_bn_delete_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='en',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('meaning', models.TextField()),
            ],
        ),
    ]
