# Generated by Django 4.2.7 on 2023-12-06 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaryapp', '0006_en'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Word',
            new_name='chomolokko',
        ),
    ]
